### PR TITLE
Add the Apple TV bundle id

### PR DESCRIPTION
**Pull request by hthmkhlf**

### CODE REVIEW

**Comment by joeblau** [comment]
THANKS! Can you just add the TV image to the repo and reference it locally? Then I'll merge this.

**Comment by hthmkhlf** [comment]
I tried to but Uploads are disabled 😄

**Comment by joeblau** [comment]
Can't you just add the image to the `/img` directory as part of your PR?

**Comment by hthmkhlf** [comment]
Done, sorry was doing it the wrong way

**Pull request merged**
