### PR TITLE
Updated for iOS 13

### PR DESCRIPTION
**Pull request by MrTechGadget**
iOS 13 brought one new app and one changed bundle ID.

Find My is the replacement for Find Friends and Find iPhone. (I added the new icon as well)
Shortcuts changed bundle IDs and in pre-installed on iOS 13.

### CODE REVIEW

**Comment by joeblau** [comment]
@MrTechGadget I was walking to work the other day and I was just thinking about this — Thanks!

**Comment by MrTechGadget** [comment]
Thanks for this resource, I use it all the time with MDM deployments.

**Comment by joeblau** [comment]
No problem. That is actually the reason I built it. We were deploying apps and we had to make sure that none of the default apps would show up except for Settings.app so I went down the rabbit hole of finding all of the bundle identifiers to block. After that I figured I would make a list because there is no way I was the only one doing this.

Now there are two of us.
giphy

**Comment by MrTechGadget** [comment]
Lol, yes! More than two for sure.

It must have been a good idea, because Apple finally got around to doing it
themselves, although only covering iOS 13 apps. :)

https://support.apple.com/guide/mdm/ios-bundle-ids-mdm90f60c1ce/web

**Comment by joeblau** [comment]
Wow... Apple's Sherlocking powers know no bounds!!

**Pull request merged**
